name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    env:
      CLANG: clang

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64

    - name: Install typescript
      run: npx tsc

    - name: make
      run: make

    - name: Deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
